### ISSUE TITLE
Registeration bugs

### ISSUE THREAD

**Issue by 1SudhanshuSingh** [1SudhanshuSingh/royalmatrimonial#39]
1. > save file name as userid_filename.extension (do not do it)
2. > input text value should be dark black
3. > remove in height and feet
4. > after putting value of height, feet and cms should be present
5. > labels of forms should be vertically center aligned
6. > for slef, relative friend, show gender options 
7. > hide gender field when selected son, daughter, brother, sister and set gender value accordingly
8. > select some options --> select option
9. > country state city value should be centeraly aligned
10. > control on mount type v call
11. > blood group, symbol change
12. >  change brother and sister enum --> no=0, 1=2, 2=3, 3=4 ,3+=5
13. > when typing in single dropdown component, enum value is not getting picked and saving in database
14. >  state county city make first item as default and send value null if nothing is selected (debug and test)

**Comment by baljitRoyalMatrimonial** [comment]
all the issue are resolved but some are pending these are : 

 2. input text value should be dark black
 
4. after putting value of height, feet and cms should be present

10. control on mount type v call
